name: SonarCloud

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ development ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0    # necessário para melhor blame/PR decoration

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      # Opcional: corre testes e gera cobertura se tiveres setup (Jest/Vitest).
      # Não falha o pipeline caso não existam testes.
      - name: Run tests (optional) with coverage
        run: npm run test --if-present -- --coverage
        continue-on-error: true

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
